# Generated by Django 5.1.4 on 2024-12-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tepFinancas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dados',
            options={'ordering': ['-data'], 'verbose_name': 'Dado', 'verbose_name_plural': 'Dados'},
        ),
        migrations.AlterField(
            model_name='dados',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
